service:
  name: typescript-serverless-boilerplate
#app: your-app-name
#tenant: your-tenant-name

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x

functions:
  hello:
    handler: lib/functions/hello.hello
    events:
      - http:
          method: get
          path: hello
